### ISSUE TITLE
Automated install from within Obsidian does fail

### ISSUE THREAD

**Issue by mgiugliano** [echo-bravo-yahoo/ego-rock#2]
Obsidian version 1.5.8 (Installer 1.5.3)

**Comment by echo-bravo-yahoo** [comment]
What OS & what error message, if any, do you get in the developer tools console? You can open the dev tools with the hotkey `<control> + <shift> + i` or `<command> + <shift> + i`. There may be relevant entries in the "console" tab; they will likely be red.

**Comment by mgiugliano** [comment]
Apologies for my earlier lack of detailed information.

Obsidian v: 1.5.8
OS v: macOS Sonoma 14.3.1

In the console, I get the following error:
```
app.js:1 Error: Request failed, status 404
    at new t (app.js:1:1782334)
    at Bq (app.js:1:1782526)
    at app.js:1:1783203
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at a (app.js:1:236367)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.installPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
```

**Comment by echo-bravo-yahoo** [comment]
Hey! Had a chance to repro, and this should be fixed now. Please re-open if you have any issues installing.
